---
abstract: Hoonlint
author:
  - 'Jeffrey Kegler'
build_requires:
  Carp: '0'
  Cwd: '0'
  Data::Dumper: '0'
  DynaLoader: '0'
  English: '0'
  Exporter: '0'
  ExtUtils::CBuilder: '0'
  ExtUtils::MakeMaker: '0'
  ExtUtils::Manifest: '0'
  ExtUtils::Mkbootstrap: '0'
  Fatal: '0'
  File::Copy: '0'
  File::Spec: '0'
  IPC::Cmd: '0'
  List::Util: '0'
  Marpa::R2: '8'
  Scalar::Util: '0'
  Test::Differences: '0'
  Test::More: '0'
  Time::Piece: '0'
  XSLoader: '0'
configure_requires:
  Carp: '0'
  Cwd: '0'
  Data::Dumper: '0'
  DynaLoader: '0'
  English: '0'
  Exporter: '0'
  ExtUtils::CBuilder: '0'
  ExtUtils::MakeMaker: '0'
  ExtUtils::Manifest: '0'
  ExtUtils::Mkbootstrap: '0'
  Fatal: '0'
  File::Copy: '0'
  File::Spec: '0'
  IPC::Cmd: '0'
  List::Util: '0'
  Marpa::R2: '8'
  Scalar::Util: '0'
  Test::Differences: '0'
  Test::More: '0'
  Time::Piece: '0'
  XSLoader: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MarpaX-Hoonlint
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  Cwd: '0'
  Data::Dumper: '0'
  DynaLoader: '0'
  English: '0'
  Exporter: '0'
  ExtUtils::CBuilder: '0'
  ExtUtils::MakeMaker: '0'
  ExtUtils::Manifest: '0'
  ExtUtils::Mkbootstrap: '0'
  Fatal: '0'
  File::Copy: '0'
  File::Spec: '0'
  IPC::Cmd: '0'
  List::Util: '0'
  Marpa::R2: '8'
  Scalar::Util: '0'
  Test::Differences: '0'
  Test::More: '0'
  Time::Piece: '0'
  XSLoader: '0'
  perl: '5.010001'
resources:
  repository: git://github.com/jeffreykegler/hoonlint.git
version: '1.008000'
x_serialization_backend: 'CPAN::Meta::YAML version 0.011'
